### ISSUE TITLE
Zce GCC  inserting (0000) unimp after functions ?

### ISSUE THREAD

**Issue by abukharmeh** [plctlab/corev-gcc#2]
Hi,

Comparing the generated executables for Zc* against the original C extension, I noticed that the compiler is introducing unnecessary (0000) unimp after functions as shown in the following screenshot. 

![image](https://user-images.githubusercontent.com/24764074/170662647-fc7d5c35-2aca-4cea-8ca2-91d49b0cd85d.png)

The left view shows the output when Zc* extensions are enabled, while the right shows C extension enabled, this leads to around 0.5%-1% waste code size and need to be fixed

Thanks,
Ibrahim.

**Comment by pz9115** [comment]
Hi @abukharmeh ,

Could you mind offer some source code for me to represent this problem,
I'm interested how this happens, thanks.

**Comment by abukharmeh** [comment]
Hi Jiawei, 

I saw this issue more than 200 times when compiling Embench benchmark. If you like, I can try to create a minimum example where it manifest so its easier for you to debug ? 

Thanks,
Ibrahim

**Comment by gfavor** [comment]
Have you checked, in both cases, what default -falign values are being used in RISC-V gcc.  I believe the current RISC-V defaults for all the -falign options are 2B - which doesn't force anything more than 2B alignment for functions, loops, and jumps (their starting addresses).  But it may be worth checking to make sure something unexpected isn't happening with these compile options.

**Comment by abukharmeh** [comment]
@gfavor  Both were compiled with the same settings apart from march, but maybe the compiler is defaulting to something else like you said, I will try to override all the defaults from the cmd-line to check if that solves it, thank you.
